CM.make("$/basis.cm");
CM.make("$/ml-yacc-lib.cm");
use "AST.sml";
use "flasl2ast.yacc.sig";
use "flasl2ast.yacc.sml";
use "flasl2ast.lex.sml";
use "flasl2ast.sml";
use "ast2flasl.sml";
use "proptableau.sml";
use "binder.sml";
Control.Print.printLength := 1000; 
Control.Print.printDepth := 1000; 
Control.Print.stringDepth := 1000; 